# Generated by Django 6.0.3 on 2026-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('online', 'En línea')], default='manual', max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono Font Awesome', max_length=50, verbose_name='Icono')),
                ('is_visible_pos', models.BooleanField(default=True, verbose_name='Visible en PDV')),
                ('is_visible_menu', models.BooleanField(default=True, verbose_name='Visible en Menú digital')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
            },
        ),
    ]
