# Generated by Django 6.0.3 on 2026-07-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_amount_received_sale_cash_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto con tarjeta'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en efectivo'),
        ),
    ]
